stages:
  - pipeline: 流水线-1
    steps:
      - name: test
        module: docker
        image: openjdk
        command:
          - javac src/Test.java
          - ls src/
          - cd src && java Test